---

# Archive Docker Image
- name: Extract Docker Image
  hosts: localhost
  tasks:
    - name: Archive docker image
      docker_image:
        name: "digital-sky-app-prod"
        tag: "1.0"
        archive_path: "/tmp/digital-sky-app-prod-1.0-di.tar"
      when: archive_docker_image

# Deploy API service
- name: Deploy server
  hosts: digital_sky_app_hosts
  user: "core"
  gather_facts: True
  tasks:

    - name: Create service directory
      file:
        path: "{{services_root_directory}}/{{app_service_name}}"
        state: directory
        mode: 0755

    - name: Copy image to server
      copy:
        src: "/tmp/{{app_image_name}}-{{app_artifact_version}}-di.tar"
        dest: "{{services_root_directory}}/{{app_service_name}}/{{app_image_name}}-{{app_artifact_version}}-di.tar"
      when: archive_docker_image

    - name: Load image from archive
      docker_image:
        name: "{{app_image_name}}"
        tag: "{{app_artifact_version}}"
        load_path: "{{services_root_directory}}/{{app_service_name}}/{{app_image_name}}-{{app_artifact_version}}-di.tar"
      when: archive_docker_image

    - name: Remove image archive
      file:
        path: "{{services_root_directory}}/{{app_service_name}}/{{app_image_name}}-{{app_artifact_version}}-di.tar"
        state: absent
      when: archive_docker_image

    - name: Resolve env properties
      template:
        src: "{{app_service_name}}-env-properties.j2"
        dest: "{{services_root_directory}}/{{app_service_name}}/env-properties.txt"
        mode: 0644
        force: yes

    - name: Re-create service container
      docker_container:
        name: "{{app_service_name}}"
        image: "{{app_image_name}}:{{app_artifact_version}}"
        env_file: "{{services_root_directory}}/{{app_service_name}}/env-properties.txt"
        state: started
        recreate: yes
        volumes:
          - "{{certs_root_directory}}:/etc/nginx/certs"
        published_ports:
          - "{{app_service_host_port}}:{{app_service_container_port}}"

